Blunt workaround for audio autoplay block
NotAllowedError: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD